#!/bin/bash

config_path="../../ColinConfig/config3.ini"
echo "Starting network emulator"
python3 ../../Emulator/emulator.py $config_path &
sleep 1
echo "Starting Receiver"
make run-receiver config=$config_path &
sleep 1
echo "Starting Sender"
make run-sender config=$config_path &
wait
# read
# pkill python3

